name = "order-discount"
type = "order_discounts"
api_version = "2023-01"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/order-discount.wasm"

[ui.paths]
create = "/"
details = "/"
